seminare/problems/urls.py
from django.urls import path

from .views import (
    ProblemDetailView,
    ProblemSetDetailView,
    ProblemSetListView,
    ProblemSetResultsView,
    ProblemSolutionView,
    SolutionPDFView,
    StatementPDFView,
)

urlpatterns = [
    path("kola/", ProblemSetListView.as_view(), name="problem_set_list"),
    path("kola/<slug>/", ProblemSetDetailView.as_view(), name="problem_set_detail"),
    path(
        "kola/<problem_set_slug>/ulohy/<int:number>/",
        ProblemDetailView.as_view(),
        name="problem_detail",
    ),
    path(
        "kola/<problem_set_slug>/ulohy/<int:number>/riesenie/",
        ProblemSolutionView.as_view(),
        name="problem_solution",
    ),
    path(
        "kola/<slug>/vysledky/",
        ProblemSetResultsView.as_view(),
        name="problem_set_results",
    ),
    path(
        "kola/<slug>/vysledky/<slug:table>/",
        ProblemSetResultsView.as_view(),
        name="problem_set_results",
    ),
    path(
        "kola/<slug>/zadania.pdf",
        StatementPDFView.as_view(),
        name="problem_set_statement_pdf",
    ),
    path(
        "kola/<slug>/vzoraky.pdf",
        SolutionPDFView.as_view(),
        name="problem_set_solution_pdf",
    ),
]

seminare/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, register_converter

from seminare.contests.views import HomepageView


class SubmitIDConverter:
    regex = "[FJT]-[0-9]+"

    def to_python(self, value):
        return value

    def to_url(self, value):
        return value


register_converter(SubmitIDConverter, "submit_id")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("oidc/", include("mozilla_django_oidc.urls")),
    path("api/", include("seminare.organizer.api")),
    path("", include("seminare.problems.urls")),
    path("", include("seminare.submits.urls")),
    path("", include("seminare.legacy.urls")),
    path("", include("seminare.users.urls")),
    path("org/", include("seminare.organizer.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("", HomepageView.as_view(), name="homepage"),
    # fallback to pages if nothing else was matched
    path("", include("seminare.content.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seminare/users/models.py
from datetime import date
from typing import TYPE_CHECKING

from django.conf import settings
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models

if TYPE_CHECKING:
    from django.db.models.fields.related_descriptors import RelatedManager


class Grade(models.TextChoices):
    YOUNG = "YNG", "<5zš"
    ZS5 = "5ZS", "5zš"
    ZS6 = "6ZS", "6zš"
    ZS7 = "7ZS", "7zš"
    ZS8 = "8ZS", "8zš"
    ZS9 = "9ZS", "9zš"
    SS1 = "1SS", "1"
    SS2 = "2SS", "2"
    SS3 = "3SS", "3"
    SS4 = "4SS", "4"
    SS5 = "5SS", "5"
    OLD = "OLD", "∞"

    @classmethod
    def is_old(cls, grade: str, is_prask=False) -> bool:
        old_grades = {cls.OLD}

        if is_prask:
            old_grades |= {cls.SS2, cls.SS3, cls.SS4, cls.SS5}

        return grade in old_grades

    @classmethod
    def is_ss(cls, grade: str) -> bool:
        return grade.startswith("SS")


class User(AbstractUser):
    id: int
    trojsten_id = models.BigIntegerField(blank=True, null=True)
    current_school = models.ForeignKey(
        "School", on_delete=models.SET_NULL, blank=True, null=True
    )
    current_school_id: int
    current_grade = models.CharField(choices=Grade.choices, max_length=3, blank=True)

    enrollment_set: "RelatedManager[Enrollment]"

    objects: "UserManager[User]"

    @property
    def profile_url(self):
        return f"https://id.trojsten.sk/profile/{self.username}/"

    @property
    def avatar_url(self):
        return f"https://id.trojsten.sk/profile/{self.username}/avatar/"

    @property
    def display_name(self):
        if self.first_name and self.last_name:
            return self.get_full_name()
        return self.username

    def update_school_info(self, school_info: dict | None):
        from seminare.users.logic.schools import get_grade_from_type_year

        if not school_info:
            self.current_school = None
            self.current_grade = ""
            return

        end_date = school_info["end_date"]
        is_expired = end_date and date.fromisoformat(end_date) < date.today()
        if is_expired:
            self.current_school = None
            self.current_grade = ""
            return

        school_data = school_info["school"]
        school, _ = School.objects.get_or_create(
            edu_id=school_data["eduid"],
            defaults={
                "name": school_data["name"],
                "address": school_data["address"],
            },
        )
        self.current_school = school

        school_type = school_info["school_type"]
        current_year = int(school_info["current_year"])
        self.current_grade = get_grade_from_type_year(school_type, current_year) or ""


class School(models.Model):
    name = models.CharField(blank=True, max_length=256)
    short_name = models.CharField(blank=True, max_length=64)
    edu_id = models.CharField(unique=True, blank=True, null=True, max_length=16)
    address = models.CharField(blank=True, max_length=256)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}, {self.address}"


class Enrollment(models.Model):
    id: int

    problem_set = models.ForeignKey("problems.ProblemSet", on_delete=models.CASCADE)
    problem_set_id: int
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    user_id: int
    school = models.ForeignKey(School, on_delete=models.CASCADE, blank=True, null=True)
    school_id: int
    grade = models.CharField(choices=Grade.choices, max_length=3)

    class Meta:
        ordering = ["problem_set", "user"]
        constraints = [
            models.UniqueConstraint(
                fields=("user", "problem_set"),
                name="enrollment_unique__user_problemset",
            ),
        ]

    def __str__(self):
        return f"{self.user} - {self.problem_set} ({self.grade})"


class ContestRole(models.Model):
    class Role(models.IntegerChoices):
        ORGANIZER = 1, "Organizátor"
        ADMINISTRATOR = 2, "Administrátor"

    id: int
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_id: int
    contest = models.ForeignKey("contests.Contest", on_delete=models.CASCADE)
    contest_id: int
    role = models.IntegerField(choices=Role.choices)

    def __str__(self):
        return f"{self.user}, {self.contest}: {self.get_role_display()}"

    if TYPE_CHECKING:

        def get_role_display(self) -> str: ...

seminare/organizer/views/problem.py
from django.db.models import QuerySet
from django.urls import reverse
from django.views.generic import CreateView, UpdateView

from seminare.contests.utils import get_current_contest
from seminare.organizer.forms import ProblemForm
from seminare.organizer.tables import ProblemTable
from seminare.organizer.views import WithProblem, WithProblemSet
from seminare.organizer.views.generic import GenericFormView, GenericTableView
from seminare.problems.models import Problem
from seminare.users.logic.permissions import is_contest_administrator
from seminare.users.mixins.permissions import (
    ContestAdminRequired,
    ContestOrganizerRequired,
)


class ProblemListView(ContestOrganizerRequired, WithProblemSet, GenericTableView):
    table_class = ProblemTable
    table_title = "Úlohy"

    def get_queryset(self) -> QuerySet[Problem]:
        return (
            Problem.objects.filter(problem_set=self.problem_set)
            .order_by("number")
            .select_related("problem_set")
        )

    def get_breadcrumbs(self):
        return [
            ("Sady úloh", reverse("org:problemset_list")),
            (self.problem_set, ""),
            ("Úlohy", ""),
        ]

    def get_table_links(self):
        if not is_contest_administrator(self.request.user, self.contest):
            return []

        return [
            (
                "green",
                "mdi:plus",
                "Pridať",
                reverse("org:problem_create", args=[self.problem_set.slug]),
            )
        ]

    def get_table_context(self):
        return {
            "is_contest_administrator": is_contest_administrator(
                self.request.user, self.contest
            ),
        }


class ProblemCreateView(
    ContestAdminRequired, WithProblemSet, GenericFormView, CreateView
):
    form_class = ProblemForm
    form_title = "Nová úloha"

    def get_form_kwargs(self):
        kw = super().get_form_kwargs()
        kw["problem_set"] = self.problem_set
        kw["contest"] = get_current_contest(self.request)
        return kw

    def get_success_url(self) -> str:
        return reverse("org:problem_list", args=[self.problem_set.slug])

    def get_breadcrumbs(self):
        return [
            ("Sady úloh", reverse("org:problemset_list")),
            (self.problem_set, ""),
            (
                "Úlohy",
                reverse("org:problem_list", args=[self.problem_set.slug]),
            ),
            ("Nová", ""),
        ]


class ProblemUpdateView(ContestAdminRequired, WithProblem, GenericFormView, UpdateView):
    form_class = ProblemForm
    form_title = "Upraviť úlohu"

    def get_form_kwargs(self):
        kw = super().get_form_kwargs()
        kw["problem_set"] = self.problem_set
        kw["contest"] = get_current_contest(self.request)
        return kw

    def get_object(self, queryset=None):
        return self.problem

    def get_success_url(self) -> str:
        return reverse("org:problem_list", args=[self.problem_set.slug])

    def get_breadcrumbs(self):
        return [
            ("Sady úloh", reverse("org:problemset_list")),
            (self.problem_set, ""),
            (
                "Úlohy",
                reverse("org:problem_list", args=[self.problem_set.slug]),
            ),
            (self.object, ""),
            ("Upraviť", ""),
        ]

seminare/problems/templates/sets/_header.html
<dl class="grid grid-cols-1 sm:grid-cols-3 -mx-2 text-sm md:-mx-4 mb-2">
  <div class="p-2 md:p-4">
    <dt class="font-semibold text-gray-900">Koniec kola:</dt>
    <dd class="text-gray-700">
      {{ problem_set.end_date }}
      {% if problem_set.is_running %}
        <span class="text-gray-500 text-xs block">({{ problem_set.end_date|timeuntil }})</span>
      {% endif %}
    </dd>
  </div>
</dl>

seminare/problems/templates/sets/_list.html
{# django #}

{% regroup sets by school_year as set_list %}

{% for school_year, sets in set_list %}
<div class="border divide-y rounded-md overflow-hidden mb-6">
  <div class="text-sm text-muted bg-gray-100 font-semibold py-3 px-4">
    {{ school_year }} / {{ school_year|add:1 }}
  </div>
  {% for problem_set in sets %}
  <div class="py-3 px-4 flex justify-between items-center flex-wrap">
    <div>
      {{ problem_set.name }}
    </div>
    <div>
      <a href="{% url "problem_set_detail" problem_set.slug %}" class="btn btn-default">Zadania</a>
      <a href="{% url "problem_set_results" problem_set.slug %}" class="btn btn-default">Výsledky</a>
    </div>
  </div>
  {% endfor %}
</div>
{% endfor %}

seminare/problems/templates/sets/_problem_list.html
{# django #}

{% include "sets/_header.html" with problem_set=problem_set %}

<div class="flex w-full mb-4 gap-2 flex-wrap">
  <a class="btn btn-primary" href="{% url "problem_set_results" problem_set.slug %}">Výsledky</a>

  {% if problem_set.statement_pdf %}
    {% if "PS" in visible_pdfs or is_organizer %}
      <a class="btn btn-default" href="{% url "problem_set_statement_pdf" problem_set.slug %}">Zadania (PDF)</a>
    {% endif %}
  {% endif %}
  {% if problem_set.solution_pdf %}
    {% if "ES" in visible_pdfs or is_organizer %}
      <a class="btn btn-default" href="{% url "problem_set_solution_pdf" problem_set.slug %}">Vzoráky (PDF)</a>
    {% endif %}
  {% endif %}
</div>

<div>
  <div class="border divide-y rounded-md overflow-hidden">
    <div class="flex justify-between text-sm text-muted bg-gray-100 font-semibold py-3 px-4">
      <div>Úloha</div>
      {% if user.is_authenticated %}
        <div>Tvoje body</div>
      {% endif %}
    </div>
    {% for problem in problems %}
      {% include "problems/_item.html" %}
    {% endfor %}
  </div>
</div>

seminare/problems/templates/sets/detail.html
{% extends "base.html" %}
{% load ui %}

{% block title %}
    {{ object }} {{ block.super }}
{% endblock %}

{% block after_menu %}
  {% url "problem_set_list" as set_list_url %}
  {% url "problem_set_detail" object.slug as set_url %}
  {% breadcrumbs "Zadania" set_list_url object set_url %}
{% endblock %}

{% block body %}
  <h1 class="text-3xl font-semibold">{{ object.name }}</h1>

  {% include "sets/_problem_list.html" with problem_set=object %}

  <hr class="my-8">

  <h2 class="text-2xl font-semibold mb-4">Archív zadaní</h2>
  {% include "./_list.html" %}
{% endblock %}

seminare/problems/templates/sets/list.html
{% extends "base.html" %}
{% load ui %}

{% block title %}
  Aktuálne zadania {{ block.super }}
{% endblock %}

{% block after_menu %}
  {% url "problem_set_list" as set_list_url %}
  {% breadcrumbs "Zadania" set_list_url %}
{% endblock %}

{% block body %}
  {% if current_sets %}
    <h1 class="text-3xl font-semibold mb-4">Aktuálne zadania</h1>

    {% for current_set in current_sets %}
      <h2 class="text-2xl font-semibold"><a href="{% url "problem_set_detail" current_set.slug %}">{{ current_set.name }}</a></h2>

      {% include "sets/_problem_list.html" with problem_set=current_set problems=current_set.problems_with_score visible_pdfs=current_set.visible_pdfs %}
      <hr class="my-8">
    {% endfor %}
  {% endif %}

  <h1 class="text-3xl font-semibold mb-4">Archív zadaní</h1>

  {% include "./_list.html" with sets=object_list %}
{% endblock %}

seminare/problems/templates/sets/results.html
{% extends "base.html" %}
{% load ui %}

{% block title %}
    {{ object }} {{ block.super }}
{% endblock %}

{% block after_menu %}
  {% url "problem_set_list" as set_list_url %}
  {% url "problem_set_detail" object.slug as set_url %}
  {% url "problem_set_results" object.slug as results_url %}
  {% breadcrumbs "Zadania" set_list_url object set_url "Výsledky" results_url selected_table_name %}
{% endblock %}

{% block body %}
  <h1 class="text-3xl font-semibold">{{ object.name }}</h1>

  {% include "sets/_header.html" with problem_set=object %}

  <div class="flex w-full mb-4">
    <a class="btn btn-primary" href="{% url "problem_set_detail" object.slug %}">Zadania</a>
  </div>

  <div class="flex w-full justify-center my-4 border rounded-md divide-x">
    {% for slug, name in result_tables.items %}
      <a class="text-center grow p-2 hover:bg-gray-50 {% if slug == selected_table %}bg-gray-100{% endif %}" href="{% url "problem_set_results" object.slug slug %}">{{ name }}</a>
    {% endfor %}
  </div>

  <div class="overflow-x-auto">
    <table class="simple-table">
      <thead>
        <tr>
          <th scope="col" class="w-0">
            #
          </th>
          <th scope="col">
            Meno
          </th>
          <th scope="col" class="w-0">
            Ročník
          </th>
          <th scope="col">
            Škola
          </th>
          {% for column_header in table.columns %}
            <th scope="col" class="!text-center">
              {% if column_header.link %}
                <a href="{{ column_header.link }}" class="link">
              {% endif %}
              <span {% if column_header.tooltip %}data-tippy-content="{{ column_header.tooltip }}"{% endif %}>
                {{ column_header.title }}
              </span>
              {% if column_header.link %}
                </a>
              {% endif %}
            </th>
          {% endfor %}
          <th class="!text-center">
            ∑
          </th>
        </tr>
      </thead>
      <tbody>
        {% for row in table.rows %}
          <tr class="{% if row.ghost %}!text-gray-400{% endif %} {% if row.enrollment.user == request.user %}bg-gray-50 font-bold{% endif %} tabular-nums">
            <td>
              {% if row.rank %}
                {{ row.rank }}.
              {% endif %}
            </td>
            <td>
              <a href="{{ row.enrollment.user.profile_url }}">
                {{ row.enrollment.user.display_name }}
              </a>
            </td>
            <td>
              {{ row.enrollment.get_grade_display }}
            </td>
            <td>
              <span data-tippy-content="{{ row.enrollment.school }}">
                {% if row.enrollment.school.short_name %}
                  {{ row.enrollment.school.short_name }}
                {% else %}
                  {{ row.enrollment.school.name }}
                {% endif %}
              </span>
            </td>
            {% for cell in row.columns %}
              <td class="text-center">
                {% if cell %}
                  <span {% if cell.display_tooltip %}data-tippy-content="{{ cell.display_tooltip }}"{% endif %} {% if cell.ghost %}class="text-gray-400"{% endif %}>
                    {{ cell.display_cell }}
                  </span>
                {% else %}
                  -
                {% endif %}
              </td>
            {% endfor %}
            <td class="text-center">
              {{ row.total }}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}