seminare/organizer/urls.py
from django.urls import path

from seminare.organizer.views import (
    dashboard,
    files,
    grading,
    menu,
    page,
    post,
    problem,
    problemset,
    role,
)

app_name = "org"

urlpatterns = [
    path("", dashboard.ContestDashboardView.as_view(), name="contest_dashboard"),
    path("kola/", problemset.ProblemSetListView.as_view(), name="problemset_list"),
    path(
        "kola/vytvorit/",
        problemset.ProblemSetCreateView.as_view(),
        name="problemset_create",
    ),
    path(
        "kola/<problem_set_slug>/",
        problemset.ProblemSetUpdateView.as_view(),
        name="problemset_update",
    ),
    path(
        "kola/<problem_set_slug>/export",
        problemset.ProblemSetCSVExportView.as_view(),
        name="problemset_csv_export",
    ),
    path(
        "kola/<problem_set_slug>/ulohy/<int:number>/opravovanie/",
        grading.GradingOverviewView.as_view(),
        name="grading_overview",
    ),
    path(
        "kola/<problem_set_slug>/ulohy/<int:number>/opravovanie/zverejnit/",
        grading.GradingPublishView.as_view(),
        name="grading_publish",
    ),
    path(
        "kola/<problem_set_slug>/ulohy/<int:number>/opravovanie/hromadne/",
        grading.BulkGradingView.as_view(),
        name="bulk_grading",
    ),
    path(
        "kola/<problem_set_slug>/ulohy/<int:number>/opravovanie/hromadne/stiahnut/",
        grading.BulkGradingDownloadView.as_view(),
        name="bulk_grading_download",
    ),
    path(
        "kola/<problem_set_slug>/ulohy/<int:number>/opravovanie/<submit_id:submit_id>/",
        grading.GradingSubmitView.as_view(),
        name="grading_submit",
    ),
    path(
        "kola/<problem_set_slug>/ulohy/",
        problem.ProblemListView.as_view(),
        name="problem_list",
    ),
    path(
        "kola/<problem_set_slug>/ulohy/<int:number>/",
        problem.ProblemUpdateView.as_view(),
        name="problem_update",
    ),
    path(
        "kola/<problem_set_slug>/ulohy/vytvorit/",
        problem.ProblemCreateView.as_view(),
        name="problem_create",
    ),
    path("menu/", menu.MenuGroupListView.as_view(), name="menu_group_list"),
    path(
        "menu/<int:pk>/",
        menu.MenuGroupUpdateView.as_view(),
        name="menu_group_update",
    ),
    path(
        "menu/<int:pk>/polozky/",
        menu.MenuItemListView.as_view(),
        name="menu_item_list",
    ),
    path(
        "menu/<int:pk>/polozky/<int:item_pk>/",
        menu.MenuItemUpdateView.as_view(),
        name="menu_item_update",
    ),
    path(
        "menu/<int:pk>/polozky/<int:item_pk>/vymazat/",
        menu.MenuItemDeleteView.as_view(),
        name="menu_item_delete",
    ),
    path(
        "menu/<int:pk>/polozky/vytvorit/",
        menu.MenuItemCreateView.as_view(),
        name="menu_item_create",
    ),
    path(
        "menu/<int:pk>/vymazat/",
        menu.MenuGroupDeleteView.as_view(),
        name="menu_group_delete",
    ),
    path(
        "menu/vytvorit/",
        menu.MenuGroupCreateView.as_view(),
        name="menu_group_create",
    ),
    path("organizatori/", role.RoleListView.as_view(), name="role_list"),
    path(
        "organizatori/<int:pk>/",
        role.RoleUpdateView.as_view(),
        name="role_update",
    ),
    path(
        "organizatori/<int:pk>/vymazat/",
        role.RoleDeleteView.as_view(),
        name="role_delete",
    ),
    path(
        "organizatori/vytvorit/",
        role.RoleCreateView.as_view(),
        name="role_create",
    ),
    path("prispevky/", post.PostListView.as_view(), name="post_list"),
    path("prispevky/<int:pk>/", post.PostUpdateView.as_view(), name="post_update"),
    path(
        "prispevky/<int:pk>/vymazat/", post.PostDeleteView.as_view(), name="post_delete"
    ),
    path("prispevky/vytvorit/", post.PostCreateView.as_view(), name="post_create"),
    path("stranky/", page.PageListView.as_view(), name="page_list"),
    path("stranky/<int:pk>/", page.PageUpdateView.as_view(), name="page_update"),
    path(
        "stranky/<int:pk>/vymazat/", page.PageDeleteView.as_view(), name="page_delete"
    ),
    path("stranky/vytvorit/", page.PageCreateView.as_view(), name="page_create"),
    path(
        "stranky/vytvorit/<path:slug>/",
        page.PageCreateView.as_view(),
        name="page_create",
    ),
    path("subory/", files.FileListView.as_view(), name="file_list"),
    path("subory/vymazat/", files.FileDeleteView.as_view(), name="file_delete"),
    path(
        "subory/novy_priecinok/", files.NewFolderView.as_view(), name="file_new_folder"
    ),
    path("subory/nahrat/", files.FileUploadView.as_view(), name="file_upload"),
]

seminare/submits/urls.py
from django.urls import path

from .views import (
    FileSubmitCreateView,
    JudgeReportView,
    JudgeSubmitCreateView,
    SubmitDetailView,
    TextSubmitCreateView,
)

urlpatterns = [
    path(
        "submits/<submit_id:submit_id>/",
        SubmitDetailView.as_view(),
        name="submit_detail",
    ),
    path(
        "submit/create/file/<int:problem>",
        FileSubmitCreateView.as_view(),
        name="file_submit",
    ),
    path(
        "submit/create/judge/<int:problem>",
        JudgeSubmitCreateView.as_view(),
        name="judge_submit",
    ),
    path(
        "submit/create/text/<int:problem>",
        TextSubmitCreateView.as_view(),
        name="text_submit",
    ),
    path(
        "submit/report/judge/",
        JudgeReportView.as_view(),
        name="judge_report",
    ),
]

seminare/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, register_converter

from seminare.contests.views import HomepageView


class SubmitIDConverter:
    regex = "[FJT]-[0-9]+"

    def to_python(self, value):
        return value

    def to_url(self, value):
        return value


register_converter(SubmitIDConverter, "submit_id")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("oidc/", include("mozilla_django_oidc.urls")),
    path("api/", include("seminare.organizer.api")),
    path("", include("seminare.problems.urls")),
    path("", include("seminare.submits.urls")),
    path("", include("seminare.legacy.urls")),
    path("", include("seminare.users.urls")),
    path("org/", include("seminare.organizer.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    path("", HomepageView.as_view(), name="homepage"),
    # fallback to pages if nothing else was matched
    path("", include("seminare.content.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seminare/organizer/views/dashboard.py
from django.views.generic import TemplateView

from seminare.organizer.views import WithContest
from seminare.users.mixins.permissions import ContestOrganizerRequired


class ContestDashboardView(ContestOrganizerRequired, WithContest, TemplateView):
    template_name = "org/contest_dashboard.html"

seminare/organizer/views/files.py
from pathlib import PurePath

from django.forms import Form
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.utils.http import urlencode

from seminare.organizer.file_utils import (
    create_folder,
    delete_subtree,
    list_folder,
    resolve_path,
    upload_file,
)
from seminare.organizer.forms import FileUploadForm, NewFolderForm
from seminare.organizer.tables import FileTable
from seminare.organizer.views import WithContest
from seminare.organizer.views.generic import (
    GenericDeleteView,
    GenericFormView,
    GenericTableView,
)
from seminare.users.mixins.permissions import ContestOrganizerRequired


class FileListView(ContestOrganizerRequired, WithContest, GenericTableView):
    table_title = "Správa súborov"
    table_class = FileTable

    def get_table_links(self):
        path = "?" + urlencode({"path": self.request.GET.get("path", "")})
        return [
            (
                "green",
                "mdi:folder-plus",
                "Priečinok",
                reverse("org:file_new_folder") + path,
            ),
            (
                "green",
                "mdi:upload",
                "Súbor",
                reverse("org:file_upload") + path,
            ),
        ]

    def get_queryset(self):  # pyright: ignore
        # Yeah, this is not exactly a QuerySet, but it is passed right to the FileTable.
        path = self.request.GET.get("path", "")
        cpath = PurePath(resolve_path(self.contest, path))
        dirs, files = list_folder(self.contest, self.request.GET.get("path", ""))
        root = self.contest.data_root

        rows = []
        if cpath != root:
            rows.append(
                {
                    "file": cpath.parent.with_name(".."),
                    "is_dir": True,
                    "rel": cpath.parent.relative_to(root),
                }
            )

        rows += [{"file": f, "is_dir": True, "rel": f.relative_to(root)} for f in dirs]
        rows += [
            {"file": f, "is_dir": False, "rel": f.relative_to(root)} for f in files
        ]
        return rows


class NewFolderView(ContestOrganizerRequired, WithContest, GenericFormView):
    form_class = NewFolderForm
    form_title = "Nový priečinok"

    def form_valid(self, form) -> HttpResponse:
        path = PurePath(self.request.GET.get("path", ""))
        create_folder(self.contest, str(path / form.cleaned_data["name"]))
        return HttpResponseRedirect(
            reverse("org:file_list") + "?" + urlencode({"path": str(path)})
        )


class FileUploadView(ContestOrganizerRequired, WithContest, GenericFormView):
    form_class = FileUploadForm
    form_title = "Nahrať súbor"
    form_multipart = True

    def form_valid(self, form) -> HttpResponse:
        path = self.request.GET.get("path", "")
        name = form.cleaned_data["file"].name
        if form.cleaned_data["name"]:
            name = form.cleaned_data["name"]

        upload_file(self.contest, path, name, form.cleaned_data["file"])
        return HttpResponseRedirect(
            reverse("org:file_list") + "?" + urlencode({"path": path})
        )


class FileDeleteView(ContestOrganizerRequired, WithContest, GenericDeleteView):
    form_class = Form

    def get_object(self, queryset=None):
        return self.request.GET.get("path")

    def form_valid(self, form) -> HttpResponse:
        delete_subtree(self.contest, self.request.GET.get("path", ""))
        path = PurePath(self.request.GET.get("path", ""))
        return HttpResponseRedirect(
            reverse("org:file_list") + "?" + urlencode({"path": str(path.parent)})
        )

seminare/organizer/views/generic.py
from django.core.exceptions import ImproperlyConfigured
from django.views.generic import DeleteView, FormView, ListView

from seminare.organizer.views import WithBreadcrumbs
from seminare.style.tables import Table


class GenericTableView(WithBreadcrumbs, ListView):
    template_name = "org/generic/table.html"

    table_title = ""
    table_class: type[Table] | None = None
    table_links: list[tuple] = []

    def get_table_title(self):
        return self.table_title

    def get_table_links(self):
        return self.table_links

    def get_table_context(self):
        return {}

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if not self.table_class:
            raise ImproperlyConfigured(
                f"{self.__class__.__name__} is missing table_class."
            )

        ctx["table"] = self.table_class()
        ctx["table_title"] = self.get_table_title()
        ctx["table_links"] = self.get_table_links()
        ctx["table_context"] = self.get_table_context()
        return ctx


class GenericFormView(WithBreadcrumbs, FormView):
    template_name = "org/generic/form.html"

    form_title = ""
    form_description = ""
    form_multipart = False
    form_submit_label = "Uložiť"
    form_header_template = None
    form_links = []

    def get_form_title(self):
        return self.form_title

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["form_title"] = self.get_form_title()
        ctx["form_description"] = self.form_description
        ctx["form_multipart"] = self.form_multipart
        ctx["form_submit_label"] = self.form_submit_label
        ctx["form_header_template"] = self.form_header_template
        ctx["form_links"] = self.get_form_links()
        return ctx

    def get_form_links(self):
        return self.form_links


class GenericDeleteView(GenericFormView, DeleteView):
    form_title = "Naozaj?"
    form_submit_label = "Vymazať"

    @property
    def form_description(self):
        return (
            f"Naozaj chceš vymazať {self.object}? Tuto akciu nebude možné vrátiť späť."
        )


class GenericFormTableView(WithBreadcrumbs, FormView, ListView):
    template_name = "org/generic/form_table.html"
    form_multipart = False
    form_submit_label = "Uložiť"
    form_table_title = ""
    form_table_links: list[tuple] = []
    table_class: type[Table] | None = None

    def get_form_table_title(self):
        return self.form_table_title

    def get_form_table_links(self):
        return self.form_table_links

    def get_form_table_context(self):
        return {}

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["form_multipart"] = self.form_multipart
        ctx["form_submit_label"] = self.form_submit_label
        if not self.table_class:
            raise ImproperlyConfigured(
                f"{self.__class__.__name__} is missing table_class."
            )

        ctx["table"] = self.table_class()
        ctx["form_table_title"] = self.get_form_table_title()
        ctx["form_table_links"] = self.get_form_table_links()
        ctx["form_table_context"] = self.get_form_table_context()
        return ctx

seminare/organizer/views/page.py
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from seminare.content.models import Page
from seminare.contests.utils import get_current_contest
from seminare.organizer.forms import PageForm
from seminare.organizer.tables import PageTable
from seminare.organizer.views import MixinProtocol
from seminare.organizer.views.generic import (
    GenericDeleteView,
    GenericFormView,
    GenericTableView,
)
from seminare.users.mixins.permissions import ContestOrganizerRequired


class WithPageQuerySet(MixinProtocol):
    def get_queryset(self):
        contest = get_current_contest(self.request)
        return Page.objects.filter(contest=contest)


class PageListView(ContestOrganizerRequired, WithPageQuerySet, GenericTableView):
    table_title = "Zoznam stránok"
    table_class = PageTable
    table_links = [("green", "mdi:plus", "Pridať", reverse_lazy("org:page_create"))]

    def get_breadcrumbs(self) -> list[tuple[str, str]]:
        return [("Stránky", "")]


class PageUpdateView(
    ContestOrganizerRequired, WithPageQuerySet, GenericFormView, UpdateView
):
    form_title = "Upraviť stránku"
    form_class = PageForm
    success_url = reverse_lazy("org:page_list")

    def get_form_kwargs(self):
        kw = super().get_form_kwargs()
        kw["contest"] = get_current_contest(self.request)
        return kw

    def get_breadcrumbs(self) -> list[tuple[str, str]]:
        return [
            ("Stránky", reverse("org:page_list")),
            (self.object, ""),
            ("Upraviť", ""),
        ]


class PageCreateView(ContestOrganizerRequired, GenericFormView, CreateView):
    form_title = "Nová stránka"
    form_class = PageForm
    success_url = reverse_lazy("org:page_list")

    def get_form_kwargs(self):
        kw = super().get_form_kwargs()
        kw["contest"] = get_current_contest(self.request)
        return kw

    def get_initial(self):
        initial = super().get_initial()
        if self.kwargs.get("slug"):
            initial["slug"] = self.kwargs["slug"]
        return initial

    def get_breadcrumbs(self) -> list[tuple[str, str]]:
        return [
            ("Stránky", reverse("org:page_list")),
            ("Nová", ""),
        ]


class PageDeleteView(ContestOrganizerRequired, WithPageQuerySet, GenericDeleteView):
    success_url = reverse_lazy("org:page_list")

    def get_breadcrumbs(self) -> list[tuple[str, str]]:
        return [
            ("Stránky", reverse("org:page_list")),
            (self.object, ""),
            ("Vymazať", ""),
        ]

seminare/organizer/templates/org/grading/_form.html
{# Grading form #}
<form class="gap-y-4 text-sm flex-1 flex flex-col" enctype="multipart/form-data" method="post" action="{% url 'org:grading_submit' problem_set.slug problem.number submit.submit_id %}" hx-boost="true">
  <textarea name="comment" class="input flex-1 {% if form.comment.errors %}border-red-600 placeholder-red-600{% endif %}" rows=7 placeholder="Komentár">{{ form.comment.value }}</textarea>

  {% if type == 'file' %}
    <div class="flex items-cemter justify-between gap-4">
      <label>
        Okomentovaný súbor
        <input type="file" name="comment_file" class="input flex-1 {% if form.comment_file.errors %}border-red-600 placeholder-red-600{% endif %}" accept="application/pdf">
      </label>
    </div>
  {% endif %}

  <div class="flex items-cemter justify-between gap-4">
    <div>
      <input type="number" name="score" value="{{ form.score.value|default_if_none:''|stringformat:'s' }}" class="input max-w-24 grow-0 {% if form.score.errors %}border-red-600 placeholder-red-600{% endif %}" step="0.5">
      <span class="font-bold ml-2 text-base {% if form.score.errors %}text-red-600{% endif %}">b</span>
    </div>
    <button type="submit" class="btn btn-blue">Uložiť</button>
  </div>
</form>

seminare/organizer/templates/org/grading/_overview_score.html
{# Overview table submit #}
<div class="flex justify-between items-center">
{% if submit %}
  {% if submit.score is None %}
    <span class="text-red-600">neohodnotené</span>
  {% else %}
    {{ submit.score|floatformat:"g" }}
  {% endif %}
  <iconify-icon icon="mdi:pencil" class="text-gray-800/40 group-hover:text-gray-800"></iconify-icon>
  <a href="{% url "org:grading_submit" problem_set.slug problem.number submit.submit_id %}" class="inset-0 absolute" {% if submit.scored_by %}data-tippy-content="{{ submit.scored_by.display_name }}"{% endif %}></a>
{% else %}
  <span class="text-gray-400">neodovzdané</span>
{% endif %}
</div>

seminare/organizer/templates/org/grading/overview.html
{% extends "org/base.html" %}
{% load ui %}

{% block title %}
{{ problem }} - hodnotenie {{ block.super }}
{% endblock title %}

{% block body %}
  {% include "org/generic/_title.html" with title=problem subtitle="Prehľad hodnotení" links=links %}

  {% if not problem.points_publicly_visible %}
    {% message "Body za túto úlohu ešte nie sú zverejnené!" "warning" %}
  {% endif %}

  <div class="overflow-x-auto mb-4">
    <table class="simple-table">
      <thead>
        <tr>
          <th>Používateľ</th>
          {% if "judge" in problem.accepted_submit_types %}
          <th class="w-32">Program</th>
          {% endif %}
          {% if "text" in problem.accepted_submit_types %}
          <th class="w-32">Text</th>
          {% endif %}
          {% if "file" in problem.accepted_submit_types %}
          <th class="w-32">Popis</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for row in users %}
        <tr id="user-{{ row.user.id }}">
          <td>{{ row.user.display_name }}</td>
          {% if "judge" in problem.accepted_submit_types %}
          <td class="relative tabular-nums {% if row.judge %}hover:bg-gray-50{% endif %} group">
            {% include "org/grading/_overview_score.html" with submit=row.judge %}
          </td>
          {% endif %}
          {% if "text" in problem.accepted_submit_types %}
          <td class="relative tabular-nums {% if row.text %}hover:bg-gray-50{% endif %} group">
            {% include "org/grading/_overview_score.html" with submit=row.text %}
          </td>
          {% endif %}
          {% if "file" in problem.accepted_submit_types %}
          <td class="relative tabular-nums {% if row.file %}hover:bg-gray-50{% endif %} group">
            {% include "org/grading/_overview_score.html" with submit=row.file %}
          </td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock body %}

seminare/organizer/templates/org/grading/submit.html
{% extends "org/base.html" %}

{% block title %}
{{ submit.submit_id }} ({{ submit.enrollment.user.display_name }}) {{ block.super }}
{% endblock title %}

{% block org_navbar_class %}{{ block.super }} hidden 2xl:block{% endblock %}

{% block org_body %}
<div class="flex flex-col md:flex-row w-full h-full max-h-screen">
  <div class="border-r w-80 shrink-0 px-4 py-3 overflow-auto space-y-1 hidden lg:block" hx-boost="true">
    <a href="{% url 'org:grading_overview' problem_set.slug problem.number %}#user-{{ submit.enrollment.user_id }}" class="link flex items-center mb-2">
      <iconify-icon icon="mdi:arrow-left" class="mr-1"></iconify-icon>
      Späť na hodnotenie úlohy
    </a>

    {% for row in other_users %}
    {% if row.submit %}
    <a href="{% url 'org:grading_submit' problem_set.slug problem.number row.submit.submit_id %}" class="block text-gray-800 px-3 py-2 hover:bg-gray-50 {% if row.user.id == submit.enrollment.user_id %}bg-gray-100 scroll-to-me{% endif %} rounded">
      <div class="flex items-center justify-between font-semibold">
        <span>{{ row.user.display_name }}</span>
        {% if row.submit.score is not None %}
        <span data-submit-score="{{ submit.id }}"class="text-green-600 whitespace-nowrap shrink-0 tabular-nums">{{ row.submit.score|floatformat:"g" }} b</span>
        {% else %}
        <span data-submit-score="{{ submit.id }}"class="text-red-600 text-sm shrink-0">neohodnotené</span>
        {% endif %}
      </div>
      {% if row.submit.comment %}
      <div class="text-sm text-gray-500">
        {{ row.submit.comment }}
      </div>
      {% endif %}
    </a>
    {% endif %}
    {% endfor %}
  </div>

  <div class="md:flex-1 overflow-auto flex min-h-[40rem] md:h-auto">
    {% include "submits/content/render.html" %}
  </div>

  <div class="border-l md:w-80 shrink-0 flex flex-col">
    <div class="font-bold text-lg pb-2 pt-3 px-4 shrink-0">Ostatné odovzdania</div>

    <div class="px-4 pb-3 pt-0 flex-1 overflow-auto space-y-1" hx-boost="true">
      {% for osubmit in other_submits %}
        {% if osubmit.type == "submit" %}
          {% with other_submit=osubmit.submit %}
            <a href="{% url 'org:grading_submit' problem_set.slug problem.number other_submit.submit_id %}" class="block text-gray-800 px-3 py-2 hover:bg-gray-50 {% if other_submit == submit %}bg-gray-100 scroll-to-me{% endif %} rounded">
              <div class="flex items-center justify-between font-semibold gap-1">
                <span class="text-ellipsis overflow-hidden text-sm">{{ other_submit.created_at }}</span>
                <span data-submit-score="{{ other_submit.id }}"class="text-green-600 whitespace-nowrap shrink-0 tabular-nums">{% if other_submit.score is not None %}{{ other_submit.score|floatformat:"g" }} b{% endif %}</span>
              </div>
            </a>
          {% endwith %}
        {% elif osubmit.type == "deadline" %}
          <div class="relative mb-2">
            <div aria-hidden="true" class="absolute inset-0 flex items-center">
              <div class="w-full border-t border-gray-300"></div>
            </div>
            <div class="relative flex justify-center">
              <span class="bg-white px-3 text-base font-semibold text-muted" data-tippy-content="{{ osubmit.time }}">{{ osubmit.label }}</span>
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>

    <div class="px-4 py-3 border-t flex-1 flex flex-col">
      <div class="font-bold text-lg mb-2">Hodnotenie</div>

      {% include "org/grading/_form.html" with type=submit.type %}
    </div>
  </div>
</div>
{% endblock org_body %}